# Generated by Django 3.0 on 2019-12-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_teammates', models.IntegerField(verbose_name='Liczba czlonkow druzyny')),
                ('number_of_points', models.IntegerField(verbose_name='Liczba punktów')),
                ('name', models.TextField(verbose_name='Nazwa druzyny')),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
