# Generated by Django 2.2.6 on 2019-12-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_teammates', models.IntegerField(default=0, verbose_name='Liczba członków drużyny')),
                ('number_of_points', models.IntegerField(default=0, verbose_name='Liczba punktów')),
                ('name_of_team', models.CharField(max_length=64, verbose_name='Nazwa drużyny')),
                ('overtime_number', models.IntegerField(blank=True, null=True, verbose_name='Liczba podana w pytaniu dogrywkowym')),
            ],
        ),
    ]
