# Generated by Django 2.2.6 on 2019-12-25 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePreferences',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('overtime_question_value', models.IntegerField(default=0, verbose_name='Wartość pytania dogrywkowego')),
                ('entry_fee', models.FloatField(default=5, verbose_name='Wpisowe [zł]')),
                ('game_status', models.BooleanField(default=False, verbose_name='Gra aktywna')),
                ('current_round', models.IntegerField(default=1, editable=False, verbose_name='Obecna runda')),
                ('st_place_reward', models.FloatField(default=0, editable=False, verbose_name='Nagroda za pierwsze miejsce [zł]')),
                ('nd_place_reward', models.FloatField(default=0, editable=False, verbose_name='Nagroda za drugie miejsce [zł]')),
                ('rd_place_reward', models.FloatField(default=0, editable=False, verbose_name='Nagroda za trzecie miejsce [zł]')),
                ('extra_reward', models.CharField(default='???', max_length=150, verbose_name='Nagroda za pytanie dogrywkowe')),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_teammates', models.IntegerField(verbose_name='Liczba członków drużyny')),
                ('number_of_points', models.IntegerField(default=0, verbose_name='Liczba punktów')),
                ('name_of_team', models.CharField(max_length=80, verbose_name='Nazwa drużyny')),
                ('overtime_number', models.IntegerField(blank=True, null=True, verbose_name='Liczba podana w pytaniu dogrywkowym')),
            ],
        ),
    ]
