# Generated by Django 2.2.6 on 2019-12-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191225_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepreferences',
            name='extra_reward',
            field=models.CharField(default='???', max_length=150, verbose_name='Nagroda za pytanie dogrywkowe'),
        ),
        migrations.AlterField(
            model_name='gamepreferences',
            name='current_round',
            field=models.IntegerField(default=1, editable=False, verbose_name='Obecna runda'),
        ),
        migrations.AlterField(
            model_name='gamepreferences',
            name='entry_fee',
            field=models.FloatField(default=5, verbose_name='Wpisowe [zł]'),
        ),
        migrations.AlterField(
            model_name='gamepreferences',
            name='extra_question_value',
            field=models.IntegerField(default=0, verbose_name='Wartość pytania dogrywkowego'),
        ),
        migrations.AlterField(
            model_name='gamepreferences',
            name='game_status',
            field=models.BooleanField(default=False, editable=False, verbose_name='Gra aktywna'),
        ),
        migrations.AlterField(
            model_name='gamepreferences',
            name='nd_place_reward',
            field=models.FloatField(default=0, editable=False, verbose_name='Nagroda za drugie miejsce [zł]'),
        ),
        migrations.AlterField(
            model_name='gamepreferences',
            name='rd_place_reward',
            field=models.FloatField(default=0, editable=False, verbose_name='Nagroda za trzecie miejsce [zł]'),
        ),
        migrations.AlterField(
            model_name='gamepreferences',
            name='st_place_reward',
            field=models.FloatField(default=0, editable=False, verbose_name='Nagroda za pierwsze miejsce [zł]'),
        ),
    ]
